config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'welcome#index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'welcome/index'
  get 'articles/myindex' => 'articles#myindex'
  get 'welcome/cobabootstrap' => 'welcome#cobabootstrap'

  namespace :v1 do
    get "articles" => "articles#index"
  end

  resources :users
  resources :articles do
    resources :comments
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  mount_uploader :image, ArticleImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  mount_uploader :avatar, AvatarUploader
  validates :email, presence: true, uniqueness: true
end

app/controllers/api_controller.rb
class ApiController < ActionController::API

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    # current_user.article.new
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
    if @article.user_id != current_user.id
      flash[:notice] = "Unauthorized user"
      redirect_to articles_path
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
  end

  def myindex
    @articles = Article.where("user_id = #{current_user.id}")
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.user_id == current_user.id
      @article.destroy
    else
      flash[:notice] = "Unauthorized user"
    end
    redirect_to articles_path
  end

  private 
  def article_params
    params.require(:article).permit(:title, :text, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    if current_user == nil
      @comment.commenter = "Anonymous"
    else
      @comment.commenter = User.find(current_user.id).fullname
      @comment.user_id = current_user.id
    end
    @comment.save
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
     
  private
    def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    # redirect_to root_path
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, alert: 'User was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :fullname, :avatar)
    end
end

app/controllers/v1/articles_controller.rb
class V1::ArticlesController < ApiController

  def index 
    data = Article.joins(:user).select("articles.*, users.email")
    render json: {status: true, result: data, error: nil}, status: 200
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
        render 'index'
    else
      redirect_to login_path
    end
  end

  def cobabootstrap
    render 'cobabootstrap'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
 <p>
    Add an image<br>
    <%= form.file_field :image %>
  </p>

  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<% if current_user %>
  Logged in as <%= current_user.fullname %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or 
  <%= link_to "Log In", login_path %>
<% end %>
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if current_user %>
  Logged in as <%= current_user.fullname %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <% controller.redirect_to login_path %>
<% end %>
<h1>Listing articles</h1>
 
<%= link_to 'New article', new_article_path %> | <%= link_to 'My Articles', articles_myindex_path %>
<table border="1">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Author</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(article) %></td>
      <td><%= article.text %></td>
      <td><%= article.user.fullname %></td>
      <%
=begin%>
 <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td> 
<%
=end%>
    </tr>
  <% end %>
</table>

app/views/articles/myindex.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if current_user %>
  Logged in as <%= current_user.fullname %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <% controller.redirect_to login_path %>
<% end %>
<h1>Listing articles</h1>
 
<%= link_to 'New article', new_article_path %> | <%= link_to 'All Articles', articles_path %>
<table border="1">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <%
=begin%>
 <th>Author</th> 
<%
=end%>
    <th colspan="2">Actions</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(article) %></td>
      <td><%= article.text %></td>
      <%
=begin%>
 <td><%= article.user.fullname %></td> 
<%
=end%>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<% if current_user %>
  Logged in as <%= current_user.fullname %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or 
  <%= link_to "Log In", login_path %>
<% end %>
<h1>New article</h1>
 
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% if current_user %>
  Logged in as <%= current_user.fullname %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= redirect_to login_path %>
<% end %>
<p>
  <h1><%= @article.title %></h1>
</p>

<%= image_tag image_url(@article.image) unless @article.image.nil? %>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h3>Comments</h3>
<%= render @article.comments %>

<h4>Add a comment:</h4>
<%= render 'comments/form' %>

<%= if @article.user_id == current_user.id then link_to 'Edit', edit_article_path(@article) end %>
<%= if @article.user_id == current_user.id then '|' end %>
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.commenter %> : </strong>
  <%= comment.body %><br>
  <%= if comment.user_id == current_user.id || comment.article.user_id == current_user.id then link_to 'Delete', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } end %>
</p>
 

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <%
=begin%>
 <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p> 
<%
=end%>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="../assets/stylesheets/application.scss">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top: 56px">
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Fullname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.fullname %></td>
        <td><%= image_tag image_url(user.avatar) unless user.avatar.nil? %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', login_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @user.fullname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', login_path %>

app/views/welcome/cobabootstrap.html.erb
<div class="container-fluid">
    <nav class="navbar navbar-expand-lg bg-dark text-white fixed-top" >
        <div class="container">
            <a class="navbar-brand">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbaResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">Service</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="container">
        <div class="row align-items-center my-5">
            <div class="col-lg-7">
                <img class="img-fluid rounded mb-4 mb-lg-0" src="http://placehold.it/900x400" alt>
            </div>
            <div class="col-lg-5">
                <h1 class="font-weight-light">Business Name or Tagline</h1>
                <p>
                This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!
                </p>
                <a class="btn btn-primary text-white" href="#">Call To Action!</a>
            </div>
        </div>
        <div class="card text-white bg-secondary my-5 py-4 text-center">
            This call to action card is a great place to showcase some important information or display a clever tagline!
        </div>
        <div class="row">  
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">Card One</h2>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-primary btn-sm">More info</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">Card Two</h2>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-primary btn-sm">More info</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">Card Three</h2>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-primary btn-sm">More info</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright Firman Ali 2019</p>        
    </div>
</footer>

app/views/welcome/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>
<% if current_user %>
  Logged in as <%= current_user.fullname %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <% controller.redirect_to login_path %>
<% end %>

<h1>Hello Rails</h1>
<%= link_to 'My Blog', controller: 'articles' %>